# main text of home
name: Julian Gil 
bio: Interest in IT

# twitter summary info 
description: A blog about technology and stuff related

picture: assets/images/image.png

url: http://juliangil97.github.io/website
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
facebook: julian.gil.52012
twitter: julian_gilb7
github: juliangil97
email: jgilb039@fiu.edu

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
